cc_test(
        name = "test_ciphertext",
        srcs = [ "test_ciphertext.cpp", "test_ciphertext.hpp" ],
        deps = [
            "@gtest//:gtest",
            "@gtest//:gtest_main",
            "//src:Ciphertext",
        ],
)
