cc_test(
        name = "test_ciphertext",
        srcs = [ "test_ciphertext.cpp", "test_ciphertext.hpp" ],
        deps = [
            "@gtest//:gtest",
            "@gtest//:gtest_main",
            "//src:Ciphertext",
        ],
)

cc_test(
        name = "test_ConvLayer",
        srcs = [ "test_ConvLayer.cpp" ],
        deps = [
            "@gtest//:gtest",
            "@gtest//:gtest_main",
            "//src:ConvLayer",
        ],
)
