cc_binary(
        name = "ResNet20",
        srcs = [ "ResNet20.cpp" ],
        deps = [ "//src:Flow", "//src:CtGraph", "//src:ConvLayer", "//src:ReLU", "//src:CleartextEvaluator", ],
        linkopts = [ "-lgvc", "-lcgraph" ],
)
